### ISSUE TITLE
Show live demo

### ISSUE THREAD

**Issue by technopagan** [technopagan/slides-in-markdown#16]
To make the tool easier to understand / judge for new users, let's host a live demo of it somewhere and link to it from the description on GitHub and the README to make the link prominent.

**Comment by mischah** [comment]
[gh-pages](https://help.github.com/articles/creating-project-pages-manually/) branch ftw :octocat: 

http://technopagan.github.io/slides-in-markdown/

**Comment by technopagan** [comment]
@mischah Perfect! Thanks! I just set it up with 0328ffa
